//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalimgareevaShoes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalimgarevaShoesEntities : DbContext
    {

        private static SalimgarevaShoesEntities _context;
        public static SalimgarevaShoesEntities GetContext()
        {
            if  (_context == null)
                _context = new SalimgarevaShoesEntities();
            return _context;
        }
        public SalimgarevaShoesEntities()
            : base("name=SalimgarevaShoesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<OrderProduct> OrderProduct { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<PickUpPoints> PickUpPoints { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Supplers> Supplers { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
