//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalimgareevaShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickUpPoints
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PickUpPoints()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int PickUpPointID { get; set; }
        public string PickUpPointAddressIndex { get; set; }
        public string PickUpPointAddressCity { get; set; }
        public string PickUpPointAddressStreet { get; set; }
        public string PickUpPointAddressHouse { get; set; }

        public string OrderPickUpPointStr
        {
            get
            {
                return PickUpPointAddressIndex + " " + PickUpPointAddressCity + " " + PickUpPointAddressStreet + " " + PickUpPointAddressHouse;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
