//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalimgareevaShoes
{
    using System;
    using System.Collections.Generic;
    using System.Windows;
    using System.Windows.Media;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public string ProductArticle { get; set; }
        public string ProductName { get; set; }
        public string ProductUnitMeasure { get; set; }
        public decimal ProductCost { get; set; }
        public int SupplerID { get; set; }
        public int ManufacturerID { get; set; }
        public int CategoryID { get; set; }
        public byte ProductCurrentDiscount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public string ProductImage { get; set; }

        public SolidColorBrush DiscountColor
        {
            get
            {
                if (ProductQuantityInStock == 0)
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("lightblue");
                if (ProductCurrentDiscount > 15)
                {
                    return (SolidColorBrush) new BrushConverter().ConvertFromString("#2E8B57");
                }
                return null;
            }
        }
        
        public SolidColorBrush CostColor
        {
            get
            {
                
                if (ProductCurrentDiscount > 0)
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("red");
                return null;
            }
        }

        public string OldCost
        {
            get
            {
                if (ProductCurrentDiscount > 0)
                    return ProductCost.ToString();
                return "";
            }
        }

        public string NewCost
        {
            get {
                return (ProductCost * (100 - ProductCurrentDiscount) / 100).ToString();
            }
        }

       


        public virtual Categories Categories { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual Supplers Supplers { get; set; }
    }
}
